kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.image.repository }}-apache-config
data:
  apache2.conf: |
    PidFile ${APACHE_PID_FILE}
    User ${APACHE_RUN_USER}
    Group ${APACHE_RUN_GROUP}
    HostnameLookups Off
    LogLevel warn
    AccessFileName .htaccess

    TraceEnable Off
    ServerSignature Off
    ServerTokens ProductOnly
    FileETag None

    KeepAlive On
    KeepAliveTimeout 5
    MaxKeepAliveRequests 100
    Timeout 300

    DefaultRuntimeDir ${APACHE_RUN_DIR}
    ErrorLog ${APACHE_LOG_DIR}/error.log

    ServerAdmin info@senshudo.tv
    ServerName control.twoangrygamers.test

    Listen 0.0.0.0:80
    Listen [::]:80

    <Directory />
      Options FollowSymLinks
      AllowOverride None
      Require all denied
    </Directory>

    <Directory /usr/share>
      AllowOverride None
      Require all granted
    </Directory>

    <Directory /var/www/>
      Options Indexes FollowSymLinks
      AllowOverride None
      Require all granted
    </Directory>

    <FilesMatch "^(\.ht(access|passwds?))$">
        Require all denied
    </FilesMatch>

    # Include module configuration:
    IncludeOptional mods-enabled/*.load
    IncludeOptional mods-enabled/*.conf

    <IfModule ssl_module>
        SSLCipherSuite ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256
        SSLProtocol all -SSLv2 -SSLv3 -TLSv1 -TLSv1.1
        SSLPassPhraseDialog  builtin

        <IfModule socache_shmcb_module>
            SSLUseStapling Off
        </IfModule>
        <IfModule !socache_shmcb_module>
            SSLSessionCache dbm:/run/apache2/ssl_gcache_data_dbm
        </IfModule>

        SSLSessionCacheTimeout  300
        Mutex                   file:/run/apache2 ssl-cache
        SSLRandomSeed startup builtin
        SSLRandomSeed connect builtin

        Listen 0.0.0.0:443
        Listen [::]:443

        AddType application/x-x509-ca-cert .crt
        AddType application/x-pkcs7-crl .crl
    </IfModule>

    LogFormat "%v:%p %h %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\"" vhost_combined
    LogFormat "%h %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\"" combined
    LogFormat "%h %l %u %t \"%r\" %>s %O" common
    LogFormat "%{Referer}i -> %U" referer
    LogFormat "%{User-agent}i" agent

    IncludeOptional conf-enabled/*.conf

    <VirtualHost *:80>
        ServerName control.twoangrygamers.test
        DocumentRoot /var/www/html
        ServerAdmin info@senshudo.tv

        <Directory "/var/www/html">
          AllowOverride All
        </Directory>
    </VirtualHost>

    <VirtualHost *:80>
        ServerName twoangrygamers.test
        ServerAlias www.twoangrygamers.test
        ServerAdmin info@senshudo.tv

        DocumentRoot /var/www/twoangrygamers.test/public
        <Directory /var/www/twoangrygamers.test/public>
            DirectoryIndex index.php
            Options Indexes FollowSymLinks
            AllowOverride All
            Require all granted
        </Directory>

        # Send apache logs to stdout and stderr
        CustomLog /proc/self/fd/1 common
        ErrorLog /proc/self/fd/2
    </VirtualHost>

    <IfModule mod_deflate.c>
        AddOutputFilterByType DEFLATE text/plain
        AddOutputFilterByType DEFLATE text/html
        AddOutputFilterByType DEFLATE text/xml
        AddOutputFilterByType DEFLATE text/css
        AddOutputFilterByType DEFLATE application/xml
        AddOutputFilterByType DEFLATE application/xhtml+xml
        AddOutputFilterByType DEFLATE application/rss+xml
        AddOutputFilterByType DEFLATE application/javascript
        AddOutputFilterByType DEFLATE application/x-javascript
        AddOutputFilterByType DEFLATE font/ttf
        AddOutputFilterByType DEFLATE font/otf
        AddOutputFilterByType DEFLATE font/woff
        AddOutputFilterByType DEFLATE font/woff2
        AddOutputFilterByType DEFLATE application/vnd.ms-fontobject
        AddOutputFilterByType DEFLATE image/svg+xml

        BrowserMatch ^Mozilla/4 gzip-only-text/html
        BrowserMatch ^Mozilla/4.0[678] no-gzip
        BrowserMatch bMSIE !no-gzip !gzip-only-text/html
        Header append Vary User-Agent
    </IfModule>

    <IfModule mod_expires.c>
        FileETag None
        Header unset ETag
        ExpiresActive On
        ExpiresByType image/* "access 1 year"
        ExpiresByType application/* "access 1 month"
        ExpiresByType text/x-javascript "access 1 month"
        ExpiresByType text/javascript "access 1 month"
        ExpiresByType text/css "access 1 month"
        ExpiresDefault "access 2 days"

        # 1 YEAR
        <FilesMatch "\.(ico|pdf|jpg|jpeg|png|gif)$">
            Header set Cache-Control "max-age=29030400, public"
            Header append Vary "Accept-Encoding"
        </FilesMatch>

        # 1 Month
        <FilesMatch "\.(js|xml|txt|css|ttf|ttc|otf|eot|woff|woff2|svg)$">
            Header set Cache-Control "max-age=2592000, public"
            Header append Vary "Accept-Encoding"
        </FilesMatch>

        # Dynamic
        <FilesMatch "\.(php|html|htm)$">
            Header set Cache-Control "max-age=0, private, no-store, no-cache, must-revalidate"
            Header append Vary "Accept-Encoding"
        </FilesMatch>
    </IfModule>

    <IfModule mod_headers.c>
        Header always set X-Xss-Protection "1; mode=block"
        Header always set X-Content-Type-Options "nosniff"
        Header always set X-Frame-Options "SAMEORIGIN"
        Header always set Referrer-Policy "strict-origin"
    </IfModule>

    # Include generic snippets of statements
    IncludeOptional conf-enabled/*.conf

    # vim: syntax=apache ts=4 sw=4 sts=4 sr noet
