replicaCount: 1
env: local
logChannel: stack
repositoryName: TwoAngryGamers
image:
  repository: twoangrygamers
  pullPolicy: IfNotPresent
  registry: twoangrygamers
projectPath: ""
xdebugEnabled: false

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  ports:
    - name: web
      port: 80

ingress:
  enabled: true
  annotations:
    ingress.kubernetes.io/enable-cors: "true"
    kubernetes.io/ingress.class: traefik
  hosts:
    - name: twoangrygamerswww
      host: www.twoangrygamers.test
      paths: ["/"]

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
